apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: test
  namespace: default
spec:
  interval: 1m0s
  url: https://github.com/cbuto/flux-test-repo
  ref:
    branch: master
