apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: test
  namespace: default
spec:
  interval: 60m0s
  wait: true
  timeout: 1m0s
  retryInterval: 1m0s
  prune: true
  force: true
  sourceRef:
    kind: GitRepository
    name: test
    namespace: default
  path: "./testapp/helm"
