apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: test
  namespace: default
spec:
  interval: 5m
  chart:
    spec:
      chart: test
      version: 0.1.0
      sourceRef:
        kind: HelmRepository
        name: test
        namespace: default
      interval: 1m
  timeout: 5m
---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: test
  namespace: default
spec:
  url: http://chartmuseum.flux-system.svc.cluster.local:8080
  interval: 10m
