apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: test
  namespace: default
spec:
  interval: 5m
  chart:
    spec:
      chart: test
      version: 0.1.0
      sourceRef:
        kind: HelmRepository
        name: chartmuseum
        namespace: default
      interval: 1m
  timeout: 5m
